# Generated by Django 5.0.9 on 2026-05-01 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uid', models.CharField(db_index=True, max_length=64, verbose_name='Session UID')),
                ('ip_hash', models.CharField(max_length=64, verbose_name='IP hash')),
                ('country', models.CharField(blank=True, default='', max_length=64, verbose_name='Mamlakat')),
                ('country_code', models.CharField(blank=True, default='', max_length=2, verbose_name='Mamlakat kodi')),
                ('city', models.CharField(blank=True, default='', max_length=64, verbose_name='Shahar')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, default='', max_length=64, verbose_name='Brauzer')),
                ('browser_version', models.CharField(blank=True, default='', max_length=32)),
                ('os', models.CharField(blank=True, default='', max_length=64, verbose_name='OS')),
                ('os_version', models.CharField(blank=True, default='', max_length=32)),
                ('device', models.CharField(blank=True, default='', max_length=64, verbose_name='Qurilma')),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlandi')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugadi')),
                ('is_bounce', models.BooleanField(default=False, verbose_name='Bounce')),
                ('page_count', models.PositiveIntegerField(default=1, verbose_name='Sahifalar soni')),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiyligi')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sites.site')),
            ],
            options={
                'verbose_name': 'Sessiya',
                'verbose_name_plural': 'Sessiyalar',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, verbose_name='URL')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='Sarlavha')),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('load_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('lcp_ms', models.PositiveIntegerField(blank=True, help_text='Largest Contentful Paint', null=True)),
                ('fcp_ms', models.PositiveIntegerField(blank=True, help_text='First Contentful Paint', null=True)),
                ('ttfb_ms', models.PositiveIntegerField(blank=True, help_text='Time To First Byte', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='sites.site')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='tracking.session')),
            ],
            options={
                'verbose_name': "Sahifa ko'rishi",
                'verbose_name_plural': "Sahifa ko'rishlari",
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('click', 'Klik'), ('form', 'Form yuborish'), ('custom', 'Custom'), ('scroll', 'Scroll')], max_length=32, verbose_name='Turi')),
                ('target', models.CharField(blank=True, default='', max_length=500, verbose_name='Maqsad')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha")),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sites.site')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.session')),
            ],
            options={
                'verbose_name': 'Hodisa',
                'verbose_name_plural': 'Hodisalar',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['site', '-started_at'], name='tracking_se_site_id_6b3121_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_uid'], name='tracking_se_session_3182ba_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['country_code'], name='tracking_se_country_dae01c_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['site', '-timestamp'], name='tracking_pa_site_id_a52c72_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session'], name='tracking_pa_session_91f461_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['site', '-timestamp'], name='tracking_ev_site_id_16ec71_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session'], name='tracking_ev_session_378e59_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type'], name='tracking_ev_type_16c4a5_idx'),
        ),
    ]
