# Generated by Django 5.0.9 on 2026-05-01 09:03

import core.apikey
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('domain', models.CharField(max_length=255, verbose_name='Domen')),
                ('api_key', models.CharField(default=core.apikey.generate_api_key, editable=False, max_length=64, unique=True, verbose_name='API kalit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Sayt',
                'verbose_name_plural': 'Saytlar',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['api_key'], name='sites_site_api_key_4e5c51_idx'), models.Index(fields=['user', '-created_at'], name='sites_site_user_id_c8c3f9_idx')],
            },
        ),
    ]
