# Generated by Django 5.0.9 on 2026-05-01 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], max_length=8, verbose_name='Format')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Bajarilmoqda'), ('done', 'Tayyor'), ('failed', 'Xato')], default='pending', max_length=16, verbose_name='Holat')),
                ('date_from', models.DateField(verbose_name='Sana boshi')),
                ('date_to', models.DateField(verbose_name='Sana oxiri')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Fayl')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hisobot',
                'verbose_name_plural': 'Hisobotlar',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='reports_rep_user_id_dcf374_idx')],
            },
        ),
    ]
